package com.example.homework_2.utils;

import com.example.homework_2.model.Student;
import org.junit.Test;


import javax.validation.constraints.AssertTrue;
import java.util.List;


import static org.junit.Assert.*;

public class XmlUtilsTest {

    @Test
    public void xmlToList() {
        String list="<list>\n" +
                "  <student>\n" +
                "    <userId>A1</userId>\n" +
                "    <password>123123</password>\n" +
                "    <name>韩娟</name>\n" +
                "    <academy>建筑学院</academy>\n" +
                "  </student>\n" +
                "  <student>\n" +
                "    <userId>A10</userId>\n" +
                "    <password>123123</password>\n" +
                "    <name>郑丽</name>\n" +
                "    <academy>建筑学院</academy>\n" +
                "  </student>\n" +
                "  <student>\n" +
                "    <userId>A100</userId>\n" +
                "    <name>邵靖</name>\n" +
                "    <academy>建筑学院</academy>\n" +
                "  </student>\n" +
                "  <student>\n" +
                "    <userId>A11</userId>\n" +
                "    <password>123123</password>\n" +
                "    <name>汤杰</name>\n" +
                "    <academy>建筑学院</academy>\n" +
                "  </student>\n" +
                "  <student>\n" +
                "    <userId>A12</userId>\n" +
                "    <password>123123</password>\n" +
                "    <name>汪勇</name>\n" +
                "    <academy>建筑学院</academy>\n" +
                "  </student>\n" +
                "  <student>\n" +
                "    <userId>A13</userId>\n" +
                "    <password>123123</password>\n" +
                "    <name>谭娟</name>\n" +
                "    <academy>建筑学院</academy>\n" +
                "  </student>\n" +
                "  <student>\n" +
                "    <userId>A14</userId>\n" +
                "    <password>123123</password>\n" +
                "    <name>高强</name>\n" +
                "    <academy>建筑学院</academy>\n" +
                "  </student>\n" +
                "  <student>\n" +
                "    <userId>A15</userId>\n" +
                "    <password>123123</password>\n" +
                "    <name>陈明</name>\n" +
                "    <academy>建筑学院</academy>\n" +
                "  </student>\n" +
                "  <student>\n" +
                "    <userId>A16</userId>\n" +
                "    <password>123123</password>\n" +
                "    <name>范丽</name>\n" +
                "    <academy>建筑学院</academy>\n" +
                "  </student>\n" +
                "  <student>\n" +
                "    <userId>A17</userId>\n" +
                "    <password>123123</password>\n" +
                "    <name>任艳</name>\n" +
                "    <academy>建筑学院</academy>\n" +
                "  </student>\n" +
                "  <student>\n" +
                "    <userId>A18</userId>\n" +
                "    <password>123123</password>\n" +
                "    <name>吕丽</name>\n" +
                "    <academy>建筑学院</academy>\n" +
                "  </student>\n" +
                "  <student>\n" +
                "    <userId>A19</userId>\n" +
                "    <password>123123</password>\n" +
                "    <name>石秀兰</name>\n" +
                "    <academy>建筑学院</academy>\n" +
                "  </student>\n" +
                "  <student>\n" +
                "    <userId>A2</userId>\n" +
                "    <password>123123</password>\n" +
                "    <name>阎勇</name>\n" +
                "    <academy>建筑学院</academy>\n" +
                "  </student>\n" +
                "  <student>\n" +
                "    <userId>A20</userId>\n" +
                "    <password>123123</password>\n" +
                "    <name>郭娜</name>\n" +
                "    <academy>建筑学院</academy>\n" +
                "  </student>\n" +
                "  <student>\n" +
                "    <userId>A21</userId>\n" +
                "    <password>123123</password>\n" +
                "    <name>邵伟</name>\n" +
                "    <academy>建筑学院</academy>\n" +
                "  </student>\n" +
                "  <student>\n" +
                "    <userId>A22</userId>\n" +
                "    <password>123123</password>\n" +
                "    <name>赵磊</name>\n" +
                "    <academy>建筑学院</academy>\n" +
                "  </student>\n" +
                "  <student>\n" +
                "    <userId>A23</userId>\n" +
                "    <password>123123</password>\n" +
                "    <name>陆洋</name>\n" +
                "    <academy>建筑学院</academy>\n" +
                "  </student>\n" +
                "  <student>\n" +
                "    <userId>A24</userId>\n" +
                "    <password>123123</password>\n" +
                "    <name>侯洋</name>\n" +
                "    <academy>建筑学院</academy>\n" +
                "  </student>\n" +
                "  <student>\n" +
                "    <userId>A25</userId>\n" +
                "    <password>123123</password>\n" +
                "    <name>戴杰</name>\n" +
                "    <academy>建筑学院</academy>\n" +
                "  </student>\n" +
                "  <student>\n" +
                "    <userId>A26</userId>\n" +
                "    <password>123123</password>\n" +
                "    <name>罗强</name>\n" +
                "    <academy>建筑学院</academy>\n" +
                "  </student>\n" +
                "  <student>\n" +
                "    <userId>A27</userId>\n" +
                "    <password>123123</password>\n" +
                "    <name>万杰</name>\n" +
                "    <academy>建筑学院</academy>\n" +
                "  </student>\n" +
                "  <student>\n" +
                "    <userId>A28</userId>\n" +
                "    <password>123123</password>\n" +
                "    <name>谢丽</name>\n" +
                "    <academy>建筑学院</academy>\n" +
                "  </student>\n" +
                "  <student>\n" +
                "    <userId>A29</userId>\n" +
                "    <password>123123</password>\n" +
                "    <name>顾丽</name>\n" +
                "    <academy>建筑学院</academy>\n" +
                "  </student>\n" +
                "  <student>\n" +
                "    <userId>A3</userId>\n" +
                "    <password>123123</password>\n" +
                "    <name>龚丽</name>\n" +
                "    <academy>建筑学院</academy>\n" +
                "  </student>\n" +
                "  <student>\n" +
                "    <userId>A30</userId>\n" +
                "    <password>123123</password>\n" +
                "    <name>田刚</name>\n" +
                "    <academy>建筑学院</academy>\n" +
                "  </student>\n" +
                "  <student>\n" +
                "    <userId>A31</userId>\n" +
                "    <password>123123</password>\n" +
                "    <name>贾娟</name>\n" +
                "    <academy>建筑学院</academy>\n" +
                "  </student>\n" +
                "  <student>\n" +
                "    <userId>A32</userId>\n" +
                "    <password>123123</password>\n" +
                "    <name>汪超</name>\n" +
                "    <academy>建筑学院</academy>\n" +
                "  </student>\n" +
                "  <student>\n" +
                "    <userId>A33</userId>\n" +
                "    <password>123123</password>\n" +
                "    <name>毛磊</name>\n" +
                "    <academy>建筑学院</academy>\n" +
                "  </student>\n" +
                "  <student>\n" +
                "    <userId>A34</userId>\n" +
                "    <password>123123</password>\n" +
                "    <name>梁艳</name>\n" +
                "    <academy>建筑学院</academy>\n" +
                "  </student>\n" +
                "  <student>\n" +
                "    <userId>A35</userId>\n" +
                "    <password>123123</password>\n" +
                "    <name>毛丽</name>\n" +
                "    <academy>建筑学院</academy>\n" +
                "  </student>\n" +
                "  <student>\n" +
                "    <userId>A36</userId>\n" +
                "    <password>123123</password>\n" +
                "    <name>龚洋</name>\n" +
                "    <academy>建筑学院</academy>\n" +
                "  </student>\n" +
                "  <student>\n" +
                "    <userId>A37</userId>\n" +
                "    <password>123123</password>\n" +
                "    <name>秦霞</name>\n" +
                "    <academy>建筑学院</academy>\n" +
                "  </student>\n" +
                "  <student>\n" +
                "    <userId>A38</userId>\n" +
                "    <password>123123</password>\n" +
                "    <name>毛强</name>\n" +
                "    <academy>建筑学院</academy>\n" +
                "  </student>\n" +
                "  <student>\n" +
                "    <userId>A39</userId>\n" +
                "    <password>123123</password>\n" +
                "    <name>秦敏</name>\n" +
                "    <academy>建筑学院</academy>\n" +
                "  </student>\n" +
                "  <student>\n" +
                "    <userId>A4</userId>\n" +
                "    <password>123123</password>\n" +
                "    <name>汪霞</name>\n" +
                "    <academy>建筑学院</academy>\n" +
                "  </student>\n" +
                "  <student>\n" +
                "    <userId>A40</userId>\n" +
                "    <password>123123</password>\n" +
                "    <name>汤娜</name>\n" +
                "    <academy>建筑学院</academy>\n" +
                "  </student>\n" +
                "  <student>\n" +
                "    <userId>A41</userId>\n" +
                "    <password>123123</password>\n" +
                "    <name>袁军</name>\n" +
                "    <academy>建筑学院</academy>\n" +
                "  </student>\n" +
                "  <student>\n" +
                "    <userId>A42</userId>\n" +
                "    <password>123123</password>\n" +
                "    <name>卢敏</name>\n" +
                "    <academy>建筑学院</academy>\n" +
                "  </student>\n" +
                "  <student>\n" +
                "    <userId>A43</userId>\n" +
                "    <password>123123</password>\n" +
                "    <name>曹超</name>\n" +
                "    <academy>建筑学院</academy>\n" +
                "  </student>\n" +
                "  <student>\n" +
                "    <userId>A44</userId>\n" +
                "    <password>123123</password>\n" +
                "    <name>龙娜</name>\n" +
                "    <academy>建筑学院</academy>\n" +
                "  </student>\n" +
                "  <student>\n" +
                "    <userId>A45</userId>\n" +
                "    <password>123123</password>\n" +
                "    <name>罗刚</name>\n" +
                "    <academy>建筑学院</academy>\n" +
                "  </student>\n" +
                "  <student>\n" +
                "    <userId>A46</userId>\n" +
                "    <password>123123</password>\n" +
                "    <name>刘伟</name>\n" +
                "    <academy>建筑学院</academy>\n" +
                "  </student>\n" +
                "  <student>\n" +
                "    <userId>A47</userId>\n" +
                "    <password>123123</password>\n" +
                "    <name>吕敏</name>\n" +
                "    <academy>建筑学院</academy>\n" +
                "  </student>\n" +
                "  <student>\n" +
                "    <userId>A48</userId>\n" +
                "    <password>123123</password>\n" +
                "    <name>苏勇</name>\n" +
                "    <academy>建筑学院</academy>\n" +
                "  </student>\n" +
                "  <student>\n" +
                "    <userId>A49</userId>\n" +
                "    <password>123123</password>\n" +
                "    <name>赵勇</name>\n" +
                "    <academy>建筑学院</academy>\n" +
                "  </student>\n" +
                "  <student>\n" +
                "    <userId>A5</userId>\n" +
                "    <password>123123</password>\n" +
                "    <name>董勇</name>\n" +
                "    <academy>建筑学院</academy>\n" +
                "  </student>\n" +
                "  <student>\n" +
                "    <userId>A50</userId>\n" +
                "    <password>123123</password>\n" +
                "    <name>廖刚</name>\n" +
                "    <academy>建筑学院</academy>\n" +
                "  </student>\n" +
                "  <student>\n" +
                "    <userId>A6</userId>\n" +
                "    <password>123123</password>\n" +
                "    <name>韩桂英</name>\n" +
                "    <academy>建筑学院</academy>\n" +
                "  </student>\n" +
                "  <student>\n" +
                "    <userId>A7</userId>\n" +
                "    <password>123123</password>\n" +
                "    <name>邱平</name>\n" +
                "    <academy>建筑学院</academy>\n" +
                "  </student>\n" +
                "  <student>\n" +
                "    <userId>A8</userId>\n" +
                "    <password>123123</password>\n" +
                "    <name>蒋丽</name>\n" +
                "    <academy>建筑学院</academy>\n" +
                "  </student>\n" +
                "  <student>\n" +
                "    <userId>A9</userId>\n" +
                "    <password>123123</password>\n" +
                "    <name>郝强</name>\n" +
                "    <academy>建筑学院</academy>\n" +
                "  </student>\n" +
                "</list>";
        List stus=XmlUtils.xmlToList(Student.class,list);
        assertEquals("",stus);
    }
}